version: '3'

includes:
  p1:
    dir: ./p1
    taskfile: ./p1/Taskfile.yml
  p2:
    dir: ./p2
    taskfile: ./p2/Taskfile.yml
  p3:
    dir: ./p3
    taskfile: ./p3/Taskfile.yml
  bonus:
    dir: ./bonus
    taskfile: ./bonus/Taskfile.yml

tasks: 
  desc: Install all depencies necessary for the projet IOT
  cmds:
  - bash .script/install_argocd.sh
  - bash .script/install_docker.sh
  - bash .script/install_helm.sh
  - bash .script/install_k3d.sh
  - bash .script/install_kubectl.sh
  - bash .script/install_vagrant.sh
  - bash .script/install_virtualbox.sh
