version: '3'

includes:
  p1:
    dir: ./p1
    taskfile: ./p1/Taskfile.yml
  p2:
    dir: ./p2
    taskfile: ./p2/Taskfile.yml
  p3:
    dir: ./p3
    taskfile: ./p3/Taskfile.yml
  bonus:
    dir: ./bonus
    taskfile: ./bonus/Taskfile.yml

tasks:
  install:
    desc: Install all depencies necessary for the projet IOT
    cmds:
    - .script/install_argocd.sh
    - .script/install_docker.sh
    - .script/install_helm.sh
    - .script/install_k3d.sh
    - .script/install_kubectl.sh
    - .script/install_vagrant.sh
    - .script/install_virtualbox.sh
