version: '3'

tasks:
  up:
    desc: Run everything to be able to run the `show` command
    cmds:
      - vagrant up
      - sudo echo "127.0.0.1  app1.com" >> /etc/hosts
      - sudo echo "127.0.0.1  app2.com" >> /etc/hosts
      - sudo echo "127.0.0.1  app3.com" >> /etc/hosts

  down:
    desc: Clean up everything
    cmds:
      - vagrant destroy -f

  show:
    desc: Run the commands needed to show that everything works fine
    cmds:
      - vagrant ssh hferraudS -c "sudo kubectl get nodes -o wide"
      - vagrant ssh hferraudS -c "ifconfig \$(ip -o -4 addr show | awk '\$4 ~ /^192\.168\.56\./ {print \$2}')"
      - vagrant ssh hferraudSW -c "ifconfig \$(ip -o -4 addr show | awk '\$4 ~ /^192\.168\.56\./ {print \$2}')"
