version: '3'

tasks:
  up:
    desc: Run everything to be able to run the `show` command, Launch create_repository when everything is up
    cmds:
      - ./scripts/setup.sh

  down:
    desc: Clean up everything
    cmds:
      - k3d cluster delete bonus

  show-status:
    desc: Show the status of pods
    cmds: 
      - kubectl get pods -n argocd
      - kubectl get pods -n gitlab


  show:
    desc: Run the commands needed to show that everything works fine
    cmds:
      - argocd admin initial-password -n argocd
      - kubectl -n gitlab get secret gitlab-gitlab-initial-root-password -o jsonpath='{.data.password}' | base64 --decode && echo
      - echo $(curl localhost:8888)