version: '3'

tasks:
  up:
    desc: Run everything to be able to run the `show` command
    cmds:
      - ./scripts/setup.sh
      - ./scripts/create_repository.sh

  down:
    desc: Clean up everything
    cmds:
      - k3d cluster delete bonus

  show:
    desc: Run the commands needed to show that everything works fine
    cmds:
      - argocd admin initial-password -n argocd
      - kubectl -n gitlab get secret gitlab-gitlab-initial-root-password -o jsonpath='{.data.password}' | base64 --decode && echo
      - echo $(curl localhost:8888)